//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posta.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HadaryEntities1 : DbContext
    {
        public HadaryEntities1()
            : base("name=HadaryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citiezen> Citiezens { get; set; }
        public virtual DbSet<custimer> custimers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    
        public virtual int baku2(string dis)
        {
            var disParameter = dis != null ?
                new ObjectParameter("dis", dis) :
                new ObjectParameter("dis", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("baku2", disParameter);
        }
    }
}
